import { useState } from 'react'
import { LayoutDashboard, Images, Users, Map, CalendarDays, BookOpen, Handshake, Settings, Search, Bell, CheckCircle2, Clock3 } from 'lucide-react'
import { artworks, mapPlaces, tours } from '../data/siteData.js'

const nav=[['Tổng quan',LayoutDashboard],['Tác phẩm',Images],['Tác giả',Users],['TOP52',Images],['HOLA Map',Map],['HOLA Tour',CalendarDays],['Stories',BookOpen],['Đối tác',Handshake],['Cài đặt',Settings]]
export default function AdminPage(){
 const [active,setActive]=useState('Tổng quan')
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="brand admin-brand">HAL<span>O</span> HOLA</div><small>ADMIN 2026</small><nav>{nav.map(([n,I])=><button className={active===n?'active':''} key={n} onClick={()=>setActive(n)}><I size={18}/>{n}</button>)}</nav></aside><section className="admin-main"><header className="admin-top"><div><h1>{active}</h1><p>Quản trị nội dung và vận hành HALO HOLA.</p></div><div><Search/><Bell/><div className="avatar">HL</div></div></header>
 {active==='Tổng quan'?<><div className="admin-stats"><div><span>Tác phẩm</span><b>428</b><small>+36 tuần này</small></div><div><span>Tác giả</span><b>196</b><small>78% đã xác minh</small></div><div><span>Địa điểm</span><b>{mapPlaces.length}</b><small>Prototype dữ liệu</small></div><div><span>Tour</span><b>{tours.length}</b><small>3 hành trình</small></div></div><div className="admin-grid"><div className="admin-panel"><h2>Tác phẩm mới</h2>{artworks.slice(0,6).map((a,i)=><div className="admin-row" key={a.slug}><img src={a.image}/><div><b>{a.title}</b><small>{a.author}</small></div><span className={`status ${i%3===0?'pending':'approved'}`}>{i%3===0?<Clock3/>:<CheckCircle2/>}{i%3===0?'Chờ duyệt':'Hợp lệ'}</span></div>)}</div><div className="admin-panel"><h2>Tiến độ chiến dịch</h2><div className="progress-item"><span>Landing & form</span><b>100%</b><i style={{width:'100%'}}/></div><div className="progress-item"><span>HOLA Map</span><b>75%</b><i style={{width:'75%'}}/></div><div className="progress-item"><span>TOP52</span><b>45%</b><i style={{width:'45%'}}/></div><div className="progress-item"><span>HOLA DAY</span><b>60%</b><i style={{width:'60%'}}/></div></div></div></>:<div className="admin-panel admin-empty"><h2>{active}</h2><p>Module {active} đã có route UI trong prototype. Dữ liệu thật sẽ nối API/database ở bước backend.</p></div>}
 </section></main>
}
