import { useState } from 'react'
import { CalendarDays, MapPin, Users, PlayCircle, Bus, Utensils, Flag, ArrowRight } from 'lucide-react'
import PageHero from '../components/PageHero.jsx'
import { tours, img } from '../data/siteData.js'

const itinerary=[['07:30','Xuất phát từ Hà Nội',Bus],['09:00','Không gian tri thức Hòa Lạc',MapPin],['11:30','Ẩm thực địa phương',Utensils],['13:00','Làng nghề & câu chuyện bản địa',Users],['15:30','Hồ Đồng Mô',MapPin],['17:00','Kết thúc hành trình',Flag]]
export default function TourPage(){
 const [selected,setSelected]=useState(1); const tour=tours[selected]
 return <main><PageHero eyebrow="NHỮNG HÀNH TRÌNH CHẠM VÀO HÒA LẠC THẬT" title="HOLA" accent="Tour" desc="Khám phá Hòa Lạc qua trải nghiệm thực tế — đi, gặp, trải nghiệm và kể lại bằng góc nhìn của bạn." image={img.lake}><div className="actions"><button className="btn btn-green">Chọn hành trình cho bạn <ArrowRight size={16}/></button><button className="btn btn-outline"><CalendarDays size={16}/> Xem lịch tour</button></div></PageHero>
 <section className="container tour-switcher">{tours.map((t,i)=><button onClick={()=>setSelected(i)} className={selected===i?'active':''} key={t.no}><img src={t.image}/><span>Tour #{t.no} · {t.dates}</span><h3>{t.title}</h3><p>{t.kicker}</p></button>)}</section>
 <section className="container section selected-tour"><div className="tour-copy"><span className="eyebrow">TOUR #{tour.no}</span><h2>{tour.title}</h2><h3>{tour.kicker}</h3><div className="tour-facts"><span><MapPin/> Hòa Lạc, Hà Nội</span><span><CalendarDays/> 1 ngày</span><span><Users/> 15–20 người</span></div><p>{tour.desc} Hành trình ưu tiên trải nghiệm thật, gặp người thật và tạo ra những câu chuyện có chiều sâu về vùng đất.</p><div className="actions"><button className="btn btn-terra">Tham gia hành trình <ArrowRight size={16}/></button><button className="btn btn-outline"><PlayCircle size={17}/> Xem recap</button></div></div><img className="tour-feature-img" src={tour.image}/></section>
 <section className="tour-content paper-bg"><div className="container section two-col"><div><h2>Lịch trình trải nghiệm</h2><div className="timeline-list">{itinerary.map(([time,title,I])=><div key={time}><span>{time}</span><I/><div><b>{title}</b><p>Khám phá, gặp gỡ và ghi lại một lát cắt của Hòa Lạc.</p></div></div>)}</div></div><div><h2>Điểm nhấn của hành trình</h2><div className="highlight-grid"><div><b>Trải nghiệm đa sắc</b><p>Thiên nhiên – văn hóa – tri thức trong một hành trình.</p></div><div><b>Người thật, chuyện thật</b><p>Lắng nghe những câu chuyện sống động từ cộng đồng.</p></div><div><b>Thực tế & tương tác</b><p>Không chỉ tham quan, mà còn quan sát và sáng tạo.</p></div><div><b>Phù hợp nhiều đối tượng</b><p>Sinh viên, creator, KTS, người yêu khám phá.</p></div></div><div className="tour-info-card"><h3>Thông tin tour</h3><p><b>Khởi hành:</b> {tour.dates}.2026</p><p><b>Số lượng:</b> 15–20 người</p><p><b>Phối hợp:</b> CLB / chuyên gia theo từng hành trình</p><p><b>Nguyên tắc:</b> Tham gia tour không tạo ưu thế khi chấm giải.</p></div></div></div></section>
 <section className="container section"><h2>Các điểm dừng nổi bật</h2><div className="place-grid">{[['ĐHQG Hà Nội',img.student],['Làng xóm Xứ Đoài',img.village],['Hồ Đồng Mô',img.lake],['Không gian kiến trúc',img.architecture],['Điểm ngắm nắng',img.sunset]].map(([n,i])=><div className="place-card" key={n}><img src={i}/><div><h3>{n}</h3><p>Một mảnh ghép trong hành trình khám phá Hòa Lạc.</p></div></div>)}</div></section>
 </main>
}
