import { useParams, Link } from 'react-router-dom'
import { Eye, Heart, MessageCircle, MapPin, Share2, ArrowRight } from 'lucide-react'
import { artworks, img } from '../data/siteData.js'
import ArtworkCard from '../components/ArtworkCard.jsx'

export default function ArtworkPage(){
 const {slug}=useParams(); const item=artworks.find(a=>a.slug===slug)||artworks[1]
 return <main className="artwork-page paper-bg"><section className="container section artwork-hero"><div className="artwork-media"><img src={item.image}/><span className="top52-badge big">TOP52 · {item.theme}</span><div className="thumb-strip">{[img.sunset,img.lake,img.green,img.hills].map((x,i)=><img key={i} src={x}/>)}</div></div><div className="artwork-info"><span className="eyebrow">TOP52 · SẮC MÀU HÒA LẠC</span><h1>{item.title}</h1><p className="lead">Khi ánh sáng chạm vào Hòa Lạc, những điều bình dị bỗng trở nên đáng nhớ hơn.</p><div className="author-row"><div className="avatar">MA</div><div><b>{item.author}</b><small>Thành viên cộng đồng HALO HOLA</small></div></div><div className="chip-wrap"><span>{item.theme}</span><span>{item.location}</span><span>Nắng</span></div><dl><div><dt>Chủ đề</dt><dd>{item.theme}</dd></div><div><dt>Địa điểm</dt><dd>{item.location}</dd></div><div><dt>Thời gian thực hiện</dt><dd>Tháng 5, 2026</dd></div></dl><div className="stat-row"><div><Eye/><b>{item.views}</b><small>Lượt xem</small></div><div><Heart/><b>842</b><small>Lượt lưu</small></div><div><MessageCircle/><b>68</b><small>Bình luận</small></div></div><div className="stack-actions"><Link className="btn btn-green" to="/hola-map"><MapPin size={17}/> Xem trên HOLA Map</Link><button className="btn btn-outline"><Share2 size={17}/> Chia sẻ góc nhìn</button></div></div></section>
 <section className="container section story-detail"><div><span className="eyebrow">CÂU CHUYỆN PHÍA SAU TÁC PHẨM</span><h2>Một buổi sáng rất Hòa Lạc</h2><p>Có những buổi sáng, Hòa Lạc khiến mình tin rằng bình yên vẫn luôn ở đây, chỉ cần ta chịu chậm lại một chút để cảm nhận.</p><p>Khoảnh khắc này được ghi lại khi ánh nắng đầu ngày trải lên mặt nước và những lớp đồi phía xa. Không gian vừa quen vừa mới, vừa gần gũi vừa đầy cảm xúc — đúng với điều HALO HOLA muốn lưu giữ.</p></div><blockquote>“Mỗi góc nhìn là một lời nhắc rằng Hòa Lạc luôn có những điều đẹp đẽ đang chờ ta khám phá.”<cite>— {item.author}</cite></blockquote></section>
 <section className="location-detail"><div className="container location-grid"><img src={img.lake}/><div><span className="eyebrow">ĐỊA ĐIỂM TRONG TÁC PHẨM</span><h2>Hồ Đồng Mô</h2><p>Một trong những không gian thiên nhiên nổi bật phía Tây Hà Nội, với mặt nước, đồi xanh và nhịp sống chậm.</p><Link to="/hola-map" className="btn btn-outline">Xem chi tiết địa điểm <ArrowRight size={16}/></Link></div><div className="mini-map large"><span><MapPin/> Hồ Đồng Mô</span></div></div></section>
 <section className="container section"><h2>Các tác phẩm cùng chủ đề</h2><div className="art-grid compact">{artworks.slice(0,4).map(a=><ArtworkCard key={a.slug} item={a}/>)}</div></section></main>
}
