import { CalendarDays, Clock3, ArrowRight, QrCode, MessageCircleQuestion, Shirt, Users } from 'lucide-react'
import PageHero from '../components/PageHero.jsx'
import { agenda, img } from '../data/siteData.js'

export default function HolaDayPage(){
 return <main><PageHero eyebrow="SỰ KIỆN THƯỜNG NIÊN CỦA HALO HOLA" title="HOLA DAY" accent="2026" desc="Ngày hội sáng tạo & khám phá Hòa Lạc — nơi 52 góc nhìn cùng hội tụ." image={img.event}><div className="event-facts"><span><CalendarDays/>28.11.2026</span><span><Clock3/>15:00–19:00</span></div><div className="actions"><button className="btn btn-green">Đăng ký tham dự <ArrowRight size={16}/></button><button className="btn btn-outline">Xem video sự kiện</button></div></PageHero>
 <section className="countdown-strip"><div className="container"><span>ĐẾM NGƯỢC ĐẾN HOLA DAY 2026</span><div><b>57</b><small>Ngày</small></div><div><b>07</b><small>Giờ</small></div><div><b>24</b><small>Phút</small></div><div><b>06</b><small>Giây</small></div></div></section>
 <section className="container section"><div className="section-heading"><div><span className="eyebrow">LỊCH TRÌNH SỰ KIỆN</span><h2>Một ngày đầy cảm hứng</h2></div><p>Gặp gỡ, trải nghiệm, cùng kiến tạo một Hòa Lạc đầy cảm hứng.</p></div><div className="agenda-grid">{agenda.map(a=><article key={a.time}><span>{a.time}</span><h3>{a.title}</h3><img src={a.image}/><p>{a.desc}</p></article>)}</div></section>
 <section className="event-map paper-bg"><div className="container section event-map-grid"><div><span className="eyebrow">KHÔNG GIAN SỰ KIỆN</span><h2>Bản đồ trải nghiệm HOLA DAY 2026</h2><p>Mỗi khu vực là một câu chuyện, một trải nghiệm và một điểm chạm với Hòa Lạc.</p><button className="btn btn-outline">Xem bản đồ chi tiết <ArrowRight size={16}/></button></div><div className="venue-map"><span className="venue v1">Triển lãm TOP52</span><span className="venue v2">HOLA TALK</span><span className="venue v3">Main Event</span><span className="venue v4">Photobooth</span><span className="venue v5">WE HOLA</span><span className="venue v6">Check-in</span></div></div></section>
 <section className="container section"><h2>Trải nghiệm không thể bỏ lỡ</h2><div className="experience-grid">{[['Triển lãm TOP52',img.event],['HOLA TALK',img.talk],['Trao giải',img.award],['WE HOLA',img.people],['Calendar 2027',img.crafts]].map(([n,i])=><article key={n}><img src={i}/><h3>{n}</h3><p>Một điểm chạm nổi bật trong hành trình HOLA DAY.</p></article>)}</div></section>
 <section className="container section qr-info-grid"><div className="qr-card"><QrCode size={92}/><div><span className="eyebrow">THAM GIA HOLA DAY 2026</span><h2>SCAN TO SAY HELLO</h2><p>Quét mã QR để đăng ký tham dự và nhận thông tin mới nhất.</p></div></div><div className="info-box"><MessageCircleQuestion/><h3>Câu hỏi thường gặp</h3><p>Sự kiện có mất phí không?</p><p>Có giới hạn độ tuổi không?</p></div><div className="info-box"><Shirt/><h3>Dress code</h3><p>Xanh lá · Be · Nâu · Trắng</p></div><div className="info-box"><Users/><h3>Cách tham gia</h3><p>Đăng ký → Xác nhận → Tham dự → Lan tỏa</p></div></section>
 </main>
}
